
name: Run Unit Tests On Pull Request

on:
  pull_request:
    branches: [ master ]

  workflow_dispatch:
  
jobs:
  build:
    runs-on: macOS-10.15
    steps:
      - uses: actions/checkout@v2
      - name: Start xcodebuild test
        run: xcodebuild clean test -workspace WhiteLabel.xcworkspace -scheme Authenticator -destination "platform=iOS Simulator,name=iPhone 12 Pro"
