name: RunUnitTestsOnPullRequests

on:
    pull_request:
        branches: [ master ]

jobs:
    test:
        runs-on: masOS-latest
        steps:
            - name: Checkout
              uses: actions/checkout@master
            - name: Start xcodebuild test
               run: xcodebuild clean test -workspace WhiteLabel.xcworkspace -scheme Authenticator -destination "platform=iOS Simulator,name=iPhone 12 Pro"
